[mysql]
mysql.poojari.store  

[backend]
backend.poojari.store

[frontend]
poojari.store

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

# comments for ansible.cfg
# 1. ansible configuration, ansible configuration example
# 2. just copy and paste with space otherwise u will get error
# 3. don't use comment in ansible.cfg
